baseURL = "https://mark.thehartleys.uk/blog/"
canonifyURLs = true
relativeURLs = false
title = "Mark Hartley"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
mainSections = ["posts"]

[pagination]
  pagerSize = 10

[params]
  description = "Enterprise Architect | AI • Cloud • BPM"
  author = "Mark Hartley"
  ShowReadingTime = true
  ShowShareButtons = true
  mainSections = ["posts"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  [params.profileMode]
  enabled = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10