baseURL = "https://mark.thehartleys.uk/blog/"
canonifyURLs = true
relativeURLs = false
title = "Mark Hartley"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
mainSections = ["posts"]

[pagination]
  pagerSize = 10

[params]
  description = "Enterprise Architect | AI • Cloud • BPM"
  author = "Mark Hartley"
  ShowReadingTime = true
  ShowShareButtons = true
  mainSections = ["posts"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/blog/posts/"
    weight = 1