baseURL = "https://mark.thehartleys.uk/blog/"
publishDir = "public/blog"
canonifyURLs = true
relativeURLs = false
title = "Mark Hartley"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
mainSections = ["posts"]

[pagination]
  pagerSize = 10

[params]
  description = "Enterprise Architect | AI • Cloud • BPM"
  author = "Mark Hartley"
  ShowReadingTime = true
  ShowShareButtons = true
  mainSections = ["posts"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  [params.profileMode]
    enabled = false
    title = "Mark Hartley"
    subtitle = "Enterprise Architect | AI • Cloud • BPM"
    imageUrl = "profile.jpg"      # put file under /static/
    imageTitle = "Me"
    imageWidth = 200
    imageHeight = 200
  [params.homeInfoParams]
    Title = "Welcome!"
    Content = "I'm Mark Hartley, a strategic Enterprise Architect and Solution Strategist with over two decades of experience designing 
               and delivering enterprise platforms across AI, Cloud, BPM, and low-code technologies.
               I’ve worked with some of the world’s most recognised organisations — from financial institutions and global 
               pharma leaders to telecoms and government — helping executive teams translate strategy into scalable, secure, and 
               innovative solutions.
               This blog is a space to share ideas, frameworks, and practical insights drawn from years of working at the intersection 
               of technology, business, and transformation.”
    enabled = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Other Posts"
    url = "/blog/posts/"
    weight = 10
  [[menu.main]]
  identifier = "cv"
  name = "Curriculum Vitae"
  url = "cv/mark-hartley-cv.pdf"
  weight = 20





