baseURL = "https://mark.thehartleys.uk/blog/"
publishDir = "public/blog"
canonifyURLs = true
relativeURLs = false
title = "Mark Hartley"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
mainSections = ["posts"]

[pagination]
  pagerSize = 10

[params]
  description = "Enterprise Architect | AI • Cloud • BPM"
  author = "Mark Hartley"
  ShowReadingTime = true
  ShowShareButtons = true
  mainSections = ["posts"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  [params.profileMode]
    enabled = false
    title = "Mark Hartley"
    subtitle = "Enterprise Architect | AI • Cloud • BPM"
    imageUrl = "profile.jpg"      # put file under /static/
    imageTitle = "Me"
    imageWidth = 200
    imageHeight = 200
  [params.homeInfoParams]
    Title = "Hi, I’m Mark"
    Content = "Enterprise Architect | AI • Cloud • BPM"
    enabled = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/blog/posts/"
    weight = 10





