name: Build Hugo and publish public/

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 👇 add this block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true
      - name: Build
        run: hugo --minify --baseURL "https://mark.thehartleys.uk/blog/"
      - name: Publish public/ to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true