name: Build & Push blog image

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "hugo.toml"
      - "nginx.conf"
      - "Dockerfile"
      - ".github/workflows/publish.yml" # was build.yml
      - "themes/**"
      - "assets/**"
      - "content/**"
      - "layouts/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write # required for ghcr.io push

env:
  IMAGE_NAME: ghcr.io/colourtr33/hartserve-blog
  HUGO_BASEURL: https://mark.thehartleys.uk/blog/
  HUGO_VERSION: 0.151.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          build-args: |
            HUGO_BASEURL=${{ env.HUGO_BASEURL }}
            HUGO_VERSION=${{ env.HUGO_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
